version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes:
      - .:/app
    ports:
      - 3030:3030

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

volumes:
  app:
  mongodb: