version: '3'

services:
  app:
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/app/test

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  app:
  mongodb: