# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  docker-tests:
    docker:
      - image: modejota/vendorvert
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Running tests in Docker container"
          command: npm run test

# Invoke jobs via workflows
workflows:
  say-hello-workflow:
    jobs:
      - docker-tests
