# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  docker-tests:
    machine:
      image: ubuntu-2204:2022.04.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Running tests in Docker container"
          command: docker run -t -v `pwd`:/app/test modejota/vendorvert

# Invoke jobs via workflows
workflows:
  docker-ci-tests:
    jobs:
      - docker-tests
