name: Update Docker Hub README

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  dockerHubDescription:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: modejota/vendorvert
