name: Update container published in DockerHub.

on:
  push:
    paths:
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: modejota/vendorvert
          tags: latest