name: CI Test using Docker image

on: [push]

jobs:
  container-tests:
    name: Execute tests from Docker image
    runs-on: ubuntu-latest
    container:
      image: modejota/vendorvert
    steps:
      - name: Run docker tests
        run: docker run -t -v `pwd`:/app/test vendorvert