name: CI Test using Docker image

on: [push]

jobs:
  container-tests:
    name: Execute tests from Docker image
    runs-on: ubuntu-latest
    container:
      image: modejota/vendorvert
      env:
        NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - run: npm run test