name: CI Test using Docker image

on: [push]

jobs:
  container-tests:
    name: Execute tests from Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull modejota/vendorvert:latest

      - name: Test using Docker image
        run:  docker run -t -v `pwd`:/app/test vendorvert